title: Computer SOS
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown

# Contacts
contacts: 
  email: email@example.com
  phone: +123 456 789
  geo: 'Hoffman Parkway Mountain view'
  iframe-map: '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3265.289292833997!2d25.243908334491298!3d35.07450386249002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x149af2d669e80ca5%3A0x3394ff5e13cd67fb!2zQXJrYWxvY2hvcmksINCT0YDQtdGG0LjRjw!5e0!3m2!1sru!2sru!4v1531414684135" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>'
